apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-master
    spec:
      containers:
      - image: cluster-apache-spark
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "/start-spark.sh"]
        name: spark-master
        ports:
        - containerPort: 8080
          name: spark-ui
        - containerPort: 7077
          name: master
        env:
          - name: SPARK_LOCAL_IP
            value: "spark-master"
          - name: SPARK_WORKLOAD
            value: "master"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spark-worker
  name: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-worker
    spec:
      containers:
      - image: cluster-apache-spark
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "/start-spark.sh"]
        name: spark-worker
        env:
          - name: SPARK_MASTER
            value: "spark://spark-master:7077"
          - name: SPARK_WORKER_CORES
            value: "1"
          - name: SPARK_WORKER_MEMORY
            value: "1G"
          - name: SPARK_DRIVER_MEMORY
            value: "1G"
          - name: SPARK_EXECUTOR_MEMORY
            value: "1G"
          - name: SPARK_WORKLOAD
            value: "worker"
          - name: SPARK_LOCAL_IP
            value: "spark-worker"
